package builder

type BuildConfig struct {
  // Should generate structure ...
  // Should initialize git repo ...
  // No dependencies ...
  // Deps[...]
  // So on ...
}

type Builder interface {
  Build(bc *BuildConfig) error 
}
